<% url = ENV.fetch('DATABASE_URL', 'postgres://localhost:5432/canvas_development') %>
common: &common
  adapter: postgresql
  url: <%= url %>
  encoding: utf8
  timeout: 5000
  prepared_statements: false
  use_qualified_names: true
  shard_name: public
  schema_search_path: "''"

production:
  <<: *common
  url: <%= url %>

development:
  <<: *common
  url: <%= url + '_development' %>

test:
  <<: *common
  url: <%= url + '_test' %>
  shard1: canvas_test_shard_1
  shard2: canvas_test_shard_2
  test_shard_1: canvas_test_shard_1
  test_shard_2: canvas_test_shard_2
